leftnav:
- identifier: 3cb12ba2-9772-11cd-9469-eba912c8bbd4
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 4201b195-399c-620e-3876-df5bfa35ec25
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 5c93f2b1-5536-7d91-878e-b2224ece1c30
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: d4d664a8-427a-e381-6e13-ce7dc8100c7a
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 9e6ebdcd-9539-a849-77cf-703a0f6ff511
  name: Video Lectures
  pageRef: /video_galleries/video-lectures
  weight: 50
